id: aad72d69-92b9-4e21-8f67-97d2a69bf8ac
description: Create ILert incident upon Keep Alert
triggers:
  - filters:
      - key: source
        value: keep
    type: alert
owners: []
services: []
steps: []
actions:
  - name: ilert-action
    provider:
      config: "{{ providers.ilert-default }}"
      type: ilert
      with:
        affectedServices:
          - impact: OPERATIONAL
            service:
              id: 339743
        message: A mock incident created with Keep!
        status: INVESTIGATING
        summary: Keep Incident {{ alert.name }}
