apiVersion: 1
groups:
  - orgId: 1
    name: System Alerts
    folder: System
    interval: 10s
    rules:
      - uid: high_cpu_alert
        title: High CPU Usage
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: sum by(instance) (rate(node_cpu_seconds_total{mode="user"}[5m])) * 100
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              range: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [1]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                    params: []
                  type: query
              expression: A
              intervalMs: 1000
              reducer: last
              type: reduce
              refId: B
        dashboardUid: system
        panelId: 1
        noDataState: NoData
        execErrState: Alerting
        for: 30s
        annotations:
          description: "CPU usage is above threshold for instance {{ $labels.instance }}"
        labels:
          severity: warning
        isPaused: false

      - uid: high_memory_alert
        title: High Memory Usage
        condition: B
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: code
              expr: ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100)
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              range: true
              refId: A
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [90]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: last
                    params: []
                  type: query
              expression: A
              intervalMs: 1000
              reducer: last
              type: reduce
              refId: B
        dashboardUid: main
        panelId: 2
        noDataState: NoData
        execErrState: Alerting
        for: 30s
        annotations:
          description: "Memory usage is above 90% for instance {{ $labels.instance }}"
        labels:
          severity: warning
        isPaused: false
