apiVersion: 1
policies:
  - orgId: 1
    receiver: "api-notifications" # Changed from api-webhook to api-notifications
    group_by: ["alertname"]
    routes:
      - receiver: "api-notifications" # Changed this too
        group_by: ["..."]
        matchers:
          - severity =~ "warning|critical"
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
