# Use the Phase Two Keycloak image as the base
FROM quay.io/phasetwo/phasetwo-keycloak:25.0.4

# Set the working directory
WORKDIR /opt/keycloak

# Copy the realm data
COPY tests/keycloak-test-realm-export.json /opt/keycloak/data/import/keep-realm.json

# Copy the custom theme
COPY keycloak/themes/keep.jar /opt/keycloak/providers/keep.jar

# Copy the last login event listener
COPY keycloak/event_listeners/last-login-event-listener-0.0.1-SNAPSHOT.jar /opt/keycloak/providers/keycloak-event-listener.jar

# Copy the custom entrypoint script and ensure it's executable
COPY --chmod=755 keycloak/keycloak_entrypoint.sh /opt/keycloak/keycloak_entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/opt/keycloak/keycloak_entrypoint.sh"]

# Expose the default Keycloak port
EXPOSE 8080


ENV KEEP_REALM=keeptest \
    KEYCLOAK_ADMIN=keep_kc_admin \
    KEYCLOAK_ADMIN_PASSWORD=keep_kc_admin \
    KC_HTTP_RELATIVE_PATH=/auth
