"""Mock alerts for Coroot provider testing."""

ALERTS_SIMULATION = [
    {
        "id": "coroot-slo-availability-frontend",
        "name": "SLO violation: frontend availability",
        "severity": "critical",
        "status": "firing",
        "lastReceived": "2024-01-15T10:30:00Z",
        "description": "SLO 'frontend availability' is violating its objective. Objective: 99.9%. Current SLI: 98.2%",
        "source": ["coroot"],
        "url": "http://coroot.example.com/p/default/slo/availability-frontend",
        "fingerprint": "coroot-slo-availability-frontend",
        "service": "frontend",
        "objective": "99.9%",
        "sli": "98.2%",
    },
    {
        "id": "coroot-app-payment-service-issue-0",
        "name": "Coroot: payment-service — High error rate",
        "severity": "high",
        "status": "firing",
        "lastReceived": "2024-01-15T10:35:00Z",
        "description": "Application 'payment-service' has a health issue: High error rate",
        "source": ["coroot"],
        "url": "http://coroot.example.com/p/default/app/payment-service",
        "fingerprint": "coroot-app-payment-service-High error rate",
        "service": "payment-service",
        "namespace": "production",
    },
    {
        "id": "coroot-app-db-proxy-unhealthy",
        "name": "Coroot: db-proxy is degraded",
        "severity": "warning",
        "status": "firing",
        "lastReceived": "2024-01-15T09:45:00Z",
        "description": "Application 'db-proxy' health state: degraded",
        "source": ["coroot"],
        "url": "http://coroot.example.com/p/default/app/db-proxy",
        "fingerprint": "coroot-app-db-proxy-unhealthy",
        "service": "db-proxy",
        "namespace": "production",
    },
]
