FROM node:20-alpine AS base

# Dependencies stage - can be built and cached separately
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Only copy package files for better caching
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci --noproxy registry.npmjs.org --maxsockets 1

# Builder stage - build the application
FROM base AS builder
WORKDIR /app

# Copy node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy application source files
# Consider copying only what's needed for the build
COPY public ./public
COPY src ./src
COPY next.config.js .
COPY tsconfig.json .
COPY package.json .
COPY .env* ./

# Disable telemetry
ENV NEXT_TELEMETRY_DISABLED 1
ENV API_URL http://localhost:8080

# Build the application
RUN npm run build

# Production stage - minimal runtime image
FROM base AS runner
ARG GIT_COMMIT_HASH=local
ARG KEEP_VERSION=local

WORKDIR /app

# Environment variables
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1
ENV GIT_COMMIT_HASH=${GIT_COMMIT_HASH}
ENV KEEP_VERSION=${KEEP_VERSION}
ENV PORT 3000
ENV POSTHOG_KEY=phc_muk9qE3TfZsX3SZ9XxX52kCGJBclrjhkP9JxAQcm1PZ
ENV POSTHOG_HOST=https://ingest.keephq.dev
ENV PUSHER_HOST=localhost
ENV PUSHER_PORT=6001
ENV PUSHER_APP_KEY=keepappkey
ENV NEXT_PUBLIC_SENTRY_DSN=https://0d4d59e3105ffe8afa27dcb95a222009@o4505515398922240.ingest.us.sentry.io/4508258058764288

# Create non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy only what's needed for production
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY entrypoint.sh /app/entrypoint.sh

# Fix permissions for OpenShift
RUN chgrp -R 0 /app && chmod -R g=u /app
USER nextjs

EXPOSE 3000

ENTRYPOINT ["/app/entrypoint.sh"]
