FROM python:3.11 as requirements-stage

WORKDIR /tmp

RUN pip install poetry

COPY ../pyproject.toml ./poetry.lock* /tmp/

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM python:3.11 as production-stage

WORKDIR /code

COPY --from=requirements-stage /tmp/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade --use-deprecated=legacy-resolver -r /code/requirements.txt

COPY ../keep /code/keep

CMD ["uvicorn", "keep.api.api:get_app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
