ALERTS = [
    {
        "scopeId": 1,
        "scope": "SERVICE",
        "name": "payment-service",
        "id0": "payment-service|default",
        "id1": "",
        "ruleName": "service_resp_time_rule",
        "alarmMessage": "Response time of service payment-service is more than 1000ms in 3 minutes of last 10 minutes",
        "startTime": 1714100000000,
        "tags": [{"key": "level", "value": "HIGH"}],
    },
    {
        "scopeId": 4,
        "scope": "ENDPOINT",
        "name": "/api/v1/checkout",
        "id0": "payment-service|/api/v1/checkout",
        "id1": "",
        "ruleName": "endpoint_sla_rule",
        "alarmMessage": "Successful rate of endpoint /api/v1/checkout is lower than 75% in 2 minutes of last 10 minutes",
        "startTime": 1714110000000,
        "tags": [{"key": "level", "value": "CRITICAL"}],
    },
    {
        "scopeId": 2,
        "scope": "SERVICE_INSTANCE",
        "name": "payment-service-pod-abc123",
        "id0": "payment-service-pod-abc123|default",
        "id1": "",
        "ruleName": "service_instance_resp_time_rule",
        "alarmMessage": "Response time of service instance payment-service-pod-abc123 is more than 1000ms in 2 minutes of last 10 minutes",
        "startTime": 1714120000000,
        "tags": [{"key": "level", "value": "WARNING"}],
    },
]
