ALERTS = {
    "title": "Device 10.10.1.147 recovered from Devices up/down",
    "hostname": "10.10.1.147",
    "device_id": "2",
    "sysDescr": "Linux node 6.8.0-54-generic #56-Ubuntu SMP PREEMPT_DYNAMIC Sat Feb  8 00:37:57 UTC 2025 x86_64",
    "sysName": "node",
    "sysContact": "Me <me@example.org>",
    "os": "linux",
    "type": "server",
    "ip": "10.10.1.147",
    "display": "10.10.1.147",
    "version": "6.8.0-54-generic",
    "hardware": "Generic x86 64-bit",
    "features": "",
    "serial": "",
    "status": "1",
    "status_reason": "",
    "location": "Sitting on the Dock of the Bay",
    "description": "",
    "notes": "",
    "uptime": "59",
    "uptime_short": "59s",
    "uptime_long": "59 seconds",
    "elapsed": "3m 7s",
    "alerted": "1",
    "alert_id": "26",
    "alert_notes": "",
    "proc": "",
    "rule_id": "13",
    "id": "38",
    "faults": "",
    "uid": "41",
    "severity": "ok",
    "rule": "{\"condition\":\"AND\",\"rules\":[{\"id\":\"macros.device_down\",\"field\":\"macros.device_down\",\"type\":\"integer\",\"input\":\"radio\",\"operator\":\"equal\",\"value\":\"1\"}],\"valid\":true}",
    "name": "Devices up/down",
    "string": "",
    "timestamp": "2025-03-04 11:01:41",
    "contacts": "",
    "state": "0",
    "msg": "Device 10.10.1.147 recovered from Devices up/down\nSeverity: ok\nTime elapsed: 3m 7s Timestamp: 2025-03-04 11:01:41\nUnique-ID: 41\nRule:  Devices up/down  Faults:\n  #1: sysObjectID => .1.3.6.1.4.1.8072.3.2.10; sysDescr => Linux node 6.8.0-54-generic #56-Ubuntu SMP PREEMPT_DYNAMIC Sat Feb  8 00:37:57 UTC 2025 x86_64; location_id => 1;\nAlert sent to:",
    "builder": "{\"condition\":\"AND\",\"rules\":[{\"id\":\"macros.device_down\",\"field\":\"macros.device_down\",\"type\":\"integer\",\"input\":\"radio\",\"operator\":\"equal\",\"value\":\"1\"}],\"valid\":true}"
}