ALERTS = {
    "critical_node_down": {
        "payload": {
            "alert_name": "Node is Down",
            "alert_message": "Node sw-core-01 is unreachable",
            "severity": "0",
            "alert_active_id": "12345",
            "alert_object_id": "67890",
            "alert_id": "789",
            "object_name": "sw-core-01",
            "object_type": "Orion.Nodes",
            "node_name": "sw-core-01",
            "ip_address": "10.0.1.1",
            "triggered_datetime": "2026-02-24T10:30:00.0000000Z",
            "acknowledged": "false",
            "acknowledged_by": "",
            "notification_type": "PROBLEM",
        },
    },
    "warning_high_cpu": {
        "payload": {
            "alert_name": "High CPU Utilization",
            "alert_message": "CPU utilization on web-server-02 is at 92%",
            "severity": "2",
            "alert_active_id": "12346",
            "alert_object_id": "67891",
            "alert_id": "790",
            "object_name": "web-server-02",
            "object_type": "Orion.Nodes",
            "node_name": "web-server-02",
            "ip_address": "10.0.2.10",
            "triggered_datetime": "2026-02-24T10:35:00.0000000Z",
            "acknowledged": "false",
            "acknowledged_by": "",
            "notification_type": "PROBLEM",
        },
    },
    "serious_interface_down": {
        "payload": {
            "alert_name": "Interface Down",
            "alert_message": "Interface GigabitEthernet0/1 on router-01 is down",
            "severity": "1",
            "alert_active_id": "12347",
            "alert_object_id": "67892",
            "alert_id": "791",
            "object_name": "GigabitEthernet0/1",
            "object_type": "Orion.NPM.Interfaces",
            "node_name": "router-01",
            "ip_address": "10.0.0.1",
            "triggered_datetime": "2026-02-24T11:00:00.0000000Z",
            "acknowledged": "false",
            "acknowledged_by": "",
            "notification_type": "PROBLEM",
        },
    },
    "recovery_node_up": {
        "payload": {
            "alert_name": "Node is Down",
            "alert_message": "Node sw-core-01 is back online",
            "severity": "0",
            "alert_active_id": "12345",
            "alert_object_id": "67890",
            "alert_id": "789",
            "object_name": "sw-core-01",
            "object_type": "Orion.Nodes",
            "node_name": "sw-core-01",
            "ip_address": "10.0.1.1",
            "triggered_datetime": "2026-02-24T10:45:00.0000000Z",
            "acknowledged": "false",
            "acknowledged_by": "",
            "notification_type": "RECOVERY",
        },
    },
    "acknowledged_alert": {
        "payload": {
            "alert_name": "Node is Down",
            "alert_message": "Node sw-core-01 is unreachable",
            "severity": "0",
            "alert_active_id": "12345",
            "alert_object_id": "67890",
            "alert_id": "789",
            "object_name": "sw-core-01",
            "object_type": "Orion.Nodes",
            "node_name": "sw-core-01",
            "ip_address": "10.0.1.1",
            "triggered_datetime": "2026-02-24T10:30:00.0000000Z",
            "acknowledged": "true",
            "acknowledged_by": "admin",
            "notification_type": "ACKNOWLEDGEMENT",
        },
    },
    "informational_volume": {
        "payload": {
            "alert_name": "Volume Usage Above Threshold",
            "alert_message": "Volume C: on db-server-01 is 78% full",
            "severity": "3",
            "alert_active_id": "12348",
            "alert_object_id": "67893",
            "alert_id": "792",
            "object_name": "C: on db-server-01",
            "object_type": "Orion.Volumes",
            "node_name": "db-server-01",
            "ip_address": "10.0.3.5",
            "triggered_datetime": "2026-02-24T11:15:00.0000000Z",
            "acknowledged": "false",
            "acknowledged_by": "",
            "notification_type": "PROBLEM",
        },
    },
}
