# Mock SolarWinds alerts data for testing and documentation purposes.
ALERTS = [
    {
        "id": "sw-alert-1",
        "name": "Node Down - Core Router",
        "status": "firing",
        "severity": "critical",
        "lastReceived": "2025-04-21T14:30:00.000000Z",
        "environment": "production",
        "service": "core-router-01",
        "source": ["solarwinds"],
        "description": "Node core-router-01 (10.0.0.1) is down.",
        "url": "https://solarwinds.example.com/Orion/NetPerfMon/NodeDetails.aspx?NetObject=N:42",
    },
    {
        "id": "sw-alert-2",
        "name": "High CPU Utilization - Web Server",
        "status": "firing",
        "severity": "warning",
        "lastReceived": "2025-04-21T14:25:00.000000Z",
        "environment": "production",
        "service": "web-server-03",
        "source": ["solarwinds"],
        "description": "CPU utilization on web-server-03 is above 90%.",
        "url": "https://solarwinds.example.com/Orion/NetPerfMon/NodeDetails.aspx?NetObject=N:55",
    },
    {
        "id": "sw-alert-3",
        "name": "Interface Down - Edge Link",
        "status": "acknowledged",
        "severity": "high",
        "lastReceived": "2025-04-21T14:20:00.000000Z",
        "environment": "production",
        "service": "edge-router-02",
        "source": ["solarwinds"],
        "description": "Interface GigabitEthernet0/1 on edge-router-02 is down.",
        "url": "https://solarwinds.example.com/Orion/NetPerfMon/NodeDetails.aspx?NetObject=N:78",
    },
    {
        "id": "sw-alert-4",
        "name": "Disk Space Low - DB Server",
        "status": "resolved",
        "severity": "warning",
        "lastReceived": "2025-04-21T14:10:00.000000Z",
        "environment": "production",
        "service": "db-server-01",
        "source": ["solarwinds"],
        "description": "Free disk space on db-server-01 has been resolved.",
        "url": "https://solarwinds.example.com/Orion/NetPerfMon/NodeDetails.aspx?NetObject=N:99",
    },
]