"""Summaries added

Revision ID: 8e5942040de6
Revises: 9ba0aeecd4d0
Create Date: 2024-07-28 16:24:58.364281

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "8e5942040de6"
down_revision = "67f1efb93c99"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incident",
        sa.Column("user_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "incident",
        sa.Column(
            "generated_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident", "generated_summary")
    op.drop_column("incident", "user_summary")
    # ### end Alembic commands ###
