"""Custom Images

Revision ID: 0b80bda47ee2
Revises: a82154690f35
Create Date: 2025-03-05 15:55:27.653706

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "0b80bda47ee2"
down_revision = "a82154690f35"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providerimage",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_blob", sa.LargeBinary(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_by", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("providerimage")
    # ### end Alembic commands ###
