"""Incident Template Name

Revision ID: 7fde94be79e4
Revises: 21d314490e6a
Create Date: 2025-02-13 09:50:43.868988

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "7fde94be79e4"
down_revision = "21d314490e6a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "incident_name_template",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.drop_column("incident_name_template")
    # ### end Alembic commands ###
