# filebeat.yml
# Option Alpha: Stable Docker container log shipping -> Logstash
# - Reads Docker json-file logs from /var/lib/docker/containers
# - Enriches events with Docker metadata (container name, labels, etc.)
# - Keeps ONLY logs from the keep-backend-elk service (with a container-name fallback)
# - Ships to Logstash (host/port configurable via env vars)

filebeat.inputs:
  - type: filestream
    id: docker-containers
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  # Keep ONLY keep-backend-elk logs.
  # Primary match: docker compose service label
  # Fallback match: container name contains keep-backend-elk
  - drop_event:
      when:
        not:
          or:
            - equals:
                docker.container.labels.com_docker_compose_service: "keep-backend-elk"
            - contains:
                docker.container.name: "keep-backend-elk"

output.logstash:
  hosts: ["${LOGSTASH_HOST:logstash}:${LOGSTASH_PORT:5044}"]

# Logging for Filebeat itself
logging.level: info
logging.to_files: false

# Optional: reduce noise from internal metrics
monitoring.enabled: false