"""Description replaced w/ user_summary

Revision ID: c91b348b94f2
Revises: 8e5942040de6
Create Date: 2024-07-29 12:51:24.496126

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import Session

from keep.api.models.db.alert import Incident

# revision identifiers, used by Alembic.
revision = "c91b348b94f2"
down_revision = "8e5942040de6"
branch_labels = None
depends_on = None

def populate_db(session):
    # we need to populate the user_summary field with the description
    incidents = session.query(Incident).all()
    for incident in incidents:
        incident.user_summary = incident.description
        session.add(incident)
        
    session.commit()
    
def depopulate_db(session):
    # we need to populate the description field with the user_summary
    incidents = session.query(Incident).all()
    for incident in incidents:
        incident.description = incident.user_summary
        session.add(incident)
        
    session.commit()

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    session = Session(op.get_bind())
    populate_db(session)
    
    op.drop_column("incident", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incident", sa.Column("description", sa.VARCHAR(), nullable=False))
    
    session = Session(op.get_bind())
    depopulate_db(session)
    
    # ### end Alembic commands ###
