"""Is Aler To Incident link ai-generated?

Revision ID: 406cec376b61
Revises: bf756df80e9d
Create Date: 2024-10-13 20:13:29.359041

"""

import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "406cec376b61"
down_revision = "bf756df80e9d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerttoincident", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_created_by_ai", sa.Boolean(), nullable=False, server_default="false"))
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerttoincident", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("is_created_by_ai")
    # ### end Alembic commands ###
