"""user_name and generated_name separation for incident model added

Revision ID: 94886bc59c11
Revises: 1c650a429672
Create Date: 2024-09-01 14:04:52.407708

"""

import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "94886bc59c11"
down_revision = "1c650a429672"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "generated_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
    
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.execute(sa.text("UPDATE incident SET user_name = name"))
        batch_op.drop_column("name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(), nullable=False))
        
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.execute(sa.text("UPDATE incident SET name = user_name"))
        batch_op.drop_column("generated_name")
        batch_op.drop_column("user_name")
    # ### end Alembic commands ###
