"""Add incidents link to runbook and timestamp

Revision ID: de84655df741
Revises: 0796be640663
Create Date: 2024-10-09 08:55:40.216359

"""

import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "de84655df741"
down_revision = "0796be640663"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runbooktoincident",
        sa.Column(
            "incident_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("runbook_id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["incident_id"], ["incident.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["runbook_id"],
            ["runbook.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("incident_id", "runbook_id"),
    )
   
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.add_column(sa.Column("runbooks_count", sa.Integer(), nullable=False))


    with op.batch_alter_table("runbook", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timestamp", sa.DateTime(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_runbook_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runbook", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runbook_timestamp"))
        batch_op.drop_column("timestamp")

    
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.drop_column("runbooks_count")
   
    op.drop_table("runbooktoincident")
    # ### end Alembic commands ###
