"""Add index to WorkflowExecution

Revision ID: 44835add2e6f
Revises: 55cc64020f6d
Create Date: 2024-12-17 11:41:23.742655

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "44835add2e6f"
down_revision = "55cc64020f6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowexecution", schema=None) as batch_op:
        batch_op.create_index(
            "idx_workflowexecution_tenant_workflow_id_timestamp",
            ["tenant_id", "workflow_id", "started"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowexecution", schema=None) as batch_op:
        batch_op.drop_index("idx_workflowexecution_tenant_workflow_id_timestamp")
    # ### end Alembic commands ###
