"""Incident linking to each other

Revision ID: bf756df80e9d
Revises: 017d759805d9
Create Date: 2024-10-08 10:47:25.326327

"""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf756df80e9d"
down_revision = "017d759805d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "same_incident_in_the_past_id",
                sqlalchemy_utils.types.uuid.UUIDType(binary=False),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            "same_incident_in_the_past_id_fk",
            "incident",
            ["same_incident_in_the_past_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.drop_constraint("same_incident_in_the_past_id_fk", type_="foreignkey")
        batch_op.drop_column("same_incident_in_the_past_id")

    # ### end Alembic commands ###
