"""incident fingerprint

Revision ID: 620b6c048091
Revises: ef0b5b0df41c
Create Date: 2024-11-10 13:06:09.620665

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "620b6c048091"
down_revision = "ef0b5b0df41c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fingerprint", sa.TEXT(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.drop_column("fingerprint")
    # ### end Alembic commands ###
