"""Add timestamp and provider_type to alertraw

Revision ID: 895fe80117aa
Revises: ef0b5b0df41c
Create Date: 2024-11-08 20:58:40.201477

"""

from datetime import datetime
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "895fe80117aa"
down_revision = "ef0b5b0df41c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alertraw",
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=True,
        ),
    )
    op.add_column(
        "alertraw",
        sa.Column("provider_type", sa.String(255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alertraw", "provider_type")
    op.drop_column("alertraw", "timestamp")
    # ### end Alembic commands ###
