"""New types for AI config

Revision ID: 3ad5308e7200
Revises: 192157fd5788
Create Date: 2024-12-01 16:40:12.655642

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3ad5308e7200"
down_revision = "3f056d747d9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("externalaiconfigandmetadata", schema=None) as batch_op:
        batch_op.alter_column(
            "settings", existing_type=sa.VARCHAR(), type_=sa.JSON(), nullable=True,
            postgresql_using="settings::json"
        )
        batch_op.alter_column(
            "settings_proposed_by_algorithm",
            existing_type=sa.VARCHAR(),
            type_=sa.JSON(),
            existing_nullable=True,
            postgresql_using="settings::json"
        )
        batch_op.alter_column(
            "feedback_logs",
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("externalaiconfigandmetadata", schema=None) as batch_op:
        batch_op.alter_column(
            "feedback_logs",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "settings_proposed_by_algorithm",
            existing_type=sa.JSON(),
            type_=sa.VARCHAR(length=255),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "settings", existing_type=sa.JSON(), type_=sa.VARCHAR(length=255), nullable=False
        )

    # ### end Alembic commands ###
