"""Provider last pull time

Revision ID: 4147d9e706c0
Revises: 92f4f93f2140
Create Date: 2024-08-05 13:09:18.851721

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4147d9e706c0"
down_revision = "92f4f93f2140"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provider", sa.Column("last_pull_time", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider", "last_pull_time")
    # ### end Alembic commands ###
