"""mappingrule type default value

Revision ID: 5d7ae55efc6a
Revises: 938b1aa62d5c
Create Date: 2024-09-18 14:08:49.363483

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5d7ae55efc6a"
down_revision = "772790c2e50a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mappingrule", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=255),
            nullable=False,
            server_default="csv",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mappingrule", schema=None) as batch_op:
        batch_op.alter_column(
            "type", existing_type=sa.VARCHAR(length=255), nullable=True
        )
    # ### end Alembic commands ###
