"""add incident severity

Revision ID: 9ab9a17c962f
Revises: 87594ea6d308
Create Date: 2024-08-18 23:59:20.638208

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ab9a17c962f"
down_revision = "87594ea6d308"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.add_column(sa.Column("severity", sa.Integer(), nullable=False, server_default=sa.text("(5)"), default=5))

    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.alter_column(
            "require_approve",
            existing_type=sa.BOOLEAN(),
            nullable=False,
            existing_server_default=sa.text("(FALSE)"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.alter_column(
            "require_approve",
            existing_type=sa.BOOLEAN(),
            nullable=True,
            existing_server_default=sa.text("(FALSE)"),
        )

    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.drop_column("severity")

    # ### end Alembic commands ###
