"""Provisioned

Revision ID: 938b1aa62d5c
Revises: 710b4ff1d19e
Create Date: 2024-09-13 10:48:16.112419

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "938b1aa62d5c"
down_revision = "710b4ff1d19e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider", schema=None) as batch_op:
        batch_op.add_column(sa.Column("provisioned", sa.Boolean(), nullable=False))

    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.add_column(sa.Column("provisioned", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.drop_column("provisioned")

    with op.batch_alter_table("provider", schema=None) as batch_op:
        batch_op.drop_column("provisioned")

    # ### end Alembic commands ###
