"""Add parent_id to Incident

Revision ID: 480d6c989911
Revises: 005efc57cc1c
Create Date: 2024-08-13 21:27:37.332793

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "480d6c989911"
down_revision = "005efc57cc1c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Notes:
    # Initially generated migration didn't work
    # (at "alembic -c keep/alembic.ini upgrade head" step) and failed with
    # error discussed here: https://stackoverflow.com/q/30378233/10186921
    # As recommended in https://stackoverflow.com/a/32510603/10186921,
    # we should use "render_as_batch=True" in "env.py" and regenerate
    # migration with it. This is what I did here, but I didn't keep "env.py"
    # updates, because it looks like all migrations will be generated
    # with "with op.batch_alter_table(..." in this case, not sure we need it.
    # Second problem was following error:
    # ValueError: Constraint must have a name
    # I tried recommendations from here:
    # https://alembic.sqlalchemy.org/en/latest/batch.html#dropping-unnamed-or-named-foreign-key-constraints
    # but it didn't help, after all I just gave the name manually (fk_incident_parent_id)
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("parent_id", sqlmodel.sql.sqltypes.GUID(), nullable=True)
        )
        batch_op.create_foreign_key("fk_incident_parent_id", "incident", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.drop_constraint("fk_incident_parent_id", type_="foreignkey")
        batch_op.drop_column("parent_id")
    # ### end Alembic commands ###
