"""Alert To Incident link history

Revision ID: 83c1020be97d
Revises: bf756df80e9d
Create Date: 2024-10-14 08:34:46.608806

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = "83c1020be97d"
down_revision = "bf756df80e9d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerttoincident", schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            "is_created_by_ai", 
            sa.Boolean(), 
            nullable=False, 
            default=False,
            server_default=expression.false()
        ))
        batch_op.add_column(sa.Column(
            "deleted_at",
            sa.DateTime(), 
            nullable=True,
        ))
        batch_op.create_primary_key(
            "pk_alert_to_incident", ["alert_id", "incident_id", "deleted_at"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerttoincident", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("is_created_by_ai")
        batch_op.drop_constraint("pk_alert_to_incident", type_="primary")
    # ### end Alembic commands ###
