"""add timestamp to AlertToIncident and drop Group tables

Revision ID: 823369ee4931
Revises: 9ab9a17c962f
Create Date: 2024-08-19 15:05:48.405420

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "823369ee4931"
down_revision = "9ab9a17c962f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alerttogroup")
    op.drop_table("group")

    with op.batch_alter_table("alerttoincident", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timestamp", sa.DateTime(), nullable=False,
                                      server_default=sa.func.current_timestamp()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerttoincident", schema=None) as batch_op:
        batch_op.drop_column("timestamp")

    op.create_table(
        "group",
        sa.Column("rule_id", sa.CHAR(length=32), nullable=True),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(), nullable=False),
        sa.Column("creation_time", sa.DATETIME(), nullable=False),
        sa.Column("group_fingerprint", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(["rule_id"], ["rule.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alerttogroup",
        sa.Column("group_id", sa.CHAR(length=32), nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.Column("alert_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alert.id"],
        ),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "alert_id"),
    )
    # ### end Alembic commands ###
