"""Add source fields to incident

Revision ID: 77353bc66243
Revises: 92f4f93f2140
Create Date: 2024-08-01 17:55:43.421781

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "77353bc66243"
down_revision = "92f4f93f2140"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incident",
        sa.Column(
            "source_provider_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "incident",
        sa.Column(
            "source_provider_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "incident",
        sa.Column(
            "source_unique_identifier",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incident", "source_unique_identifier")
    op.drop_column("incident", "source_provider_type")
    op.drop_column("incident", "source_provider_id")
    # ### end Alembic commands ###
