"""is_valid flag to workflow

Revision ID: b4caf6779ec1
Revises: 493f217af6b6
Create Date: 2024-09-26 19:43:45.169045

"""

import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b4caf6779ec1"
down_revision = "493f217af6b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("workflow", schema=None) as batch_op:
        # Add the column with default=True for new records
        batch_op.add_column(
            sa.Column(
                "is_valid", sa.Boolean(), nullable=False, server_default=sa.true()
            )
        )

    # Update existing rows to set 'is_valid' to True
    op.execute("UPDATE workflow SET is_valid = TRUE")

    # Remove the server_default as it's not needed after the column is populated for old records
    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.alter_column("is_valid", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.drop_column("is_valid")
