"""Alert To Incident link history

Revision ID: 83c1020be97d
Revises: bf756df80e9d
Create Date: 2024-10-14 08:34:46.608806

"""

import sqlalchemy as sa
from sqlalchemy import inspect
from alembic import op
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = "83c1020be97d"
down_revision = "bf756df80e9d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)

    existing_primary_key = inspector.get_pk_constraint('alerttoincident', schema=None)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerttoincident", schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            "is_created_by_ai", 
            sa.Boolean(), 
            nullable=False, 
            default=False,
            server_default=expression.false()
        ))
        batch_op.add_column(sa.Column(
            "deleted_at",
            sa.DateTime(), 
            nullable=True,
        ))
        
        # In SQLite the PK has no name and could be overwritten, in PG and others we need to Drop it first
        if not existing_primary_key['name'] is None:
            batch_op.drop_constraint(existing_primary_key['name'], type_="primary")

        batch_op.create_primary_key(
            "alerttoincident_pkey", ["alert_id", "incident_id", "deleted_at"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    inspector = inspect(conn)

    existing_primary_key = inspector.get_pk_constraint('alerttoincident', schema=None)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerttoincident", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("is_created_by_ai")

        if not existing_primary_key['name'] is None:
            batch_op.drop_constraint(existing_primary_key['name'], type_="primary")

        batch_op.create_primary_key(
            "alerttoincident_pkey", ["alert_id", "incident_id"]
        )
    # ### end Alembic commands ###
