"""Maintenance Windows

Revision ID: 70671c95028e
Revises: 94886bc59c11
Create Date: 2024-09-02 12:07:09.147349

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "70671c95028e"
down_revision = "94886bc59c11"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenancewindowrule",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cel_query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("maintenancewindowrule", schema=None) as batch_op:
        batch_op.create_index(
            "ix_maintenance_rule_tenant_id", ["tenant_id"], unique=False
        )
        batch_op.create_index(
            "ix_maintenance_rule_tenant_id_end_time",
            ["tenant_id", "end_time"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("maintenancewindowrule", schema=None) as batch_op:
        batch_op.drop_index("ix_maintenance_rule_tenant_id_end_time")
        batch_op.drop_index("ix_maintenance_rule_tenant_id")

    op.drop_table("maintenancewindowrule")
    # ### end Alembic commands ###
