"""add suppress to mw

Revision ID: 49e7c02579db
Revises: 70671c95028e
Create Date: 2024-09-03 10:08:21.612949

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "49e7c02579db"
down_revision = "70671c95028e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("maintenancewindowrule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("suppress", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("maintenancewindowrule", schema=None) as batch_op:
        batch_op.drop_column("suppress")
    # ### end Alembic commands ###
