"""Adding alertaudit table

Revision ID: c37ec8f6db3e
Revises: 54c1252b2c8a
Create Date: 2024-07-15 15:10:51.175030

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c37ec8f6db3e"
down_revision = "54c1252b2c8a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alertaudit",
        sa.Column("id", sqlmodel.sql.sqltypes.types.Uuid(), nullable=False),
        sa.Column("fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tenant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_alert_audit_fingerprint", "alertaudit", ["fingerprint"], unique=False
    )
    op.create_index(
        "ix_alert_audit_tenant_id", "alertaudit", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_alert_audit_tenant_id_fingerprint",
        "alertaudit",
        ["tenant_id", "fingerprint"],
        unique=False,
    )
    op.create_index(
        "ix_alert_audit_timestamp", "alertaudit", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_alert_audit_timestamp", table_name="alertaudit")
    op.drop_index("ix_alert_audit_tenant_id_fingerprint", table_name="alertaudit")
    op.drop_index("ix_alert_audit_tenant_id", table_name="alertaudit")
    op.drop_index("ix_alert_audit_fingerprint", table_name="alertaudit")
    op.drop_table("alertaudit")
    # ### end Alembic commands ###
