"""auto delete provider logs

Revision ID: 0dafe96ea97f
Revises: e663a98b1142
Create Date: 2025-04-04 21:48:38.282584

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0dafe96ea97f"
down_revision = "e663a98b1142"
branch_labels = None
depends_on = None


def upgrade() -> None:

    with op.batch_alter_table("providerexecutionlog", schema=None) as batch_op:
        batch_op.alter_column(
            "provider_id", existing_type=mysql.VARCHAR(length=255), nullable=True
        )
        batch_op.drop_constraint("providerexecutionlog_ibfk_1", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "provider", ["provider_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("providerexecutionlog", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "providerexecutionlog_ibfk_1", "provider", ["provider_id"], ["id"]
        )
        batch_op.alter_column(
            "provider_id", existing_type=mysql.VARCHAR(length=255), nullable=False
        )
    # ### end Alembic commands ###
