"""restore_idx_status_started_index

Revision ID: 59991b568c7d
Revises: 78777e6b12d3
Create Date: 2025-04-08 10:43:53.361024

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "59991b568c7d"
down_revision = "78777e6b12d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the index exists before creating it
    if op.get_bind().dialect.name == "sqlite":
        # SQLite does not support querying for index existence directly, so we attempt to create it
        op.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_status_started
            ON workflowexecution (status, started)
            """
        )
    elif op.get_bind().dialect.name == "mysql":
        try:
            op.execute(
                """
                CREATE INDEX idx_status_started
                ON workflowexecution (status(255), started)
                """
            )
        except Exception as e:
            # if it fails, it means the index already exists
            pass

    elif op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_class c
                    JOIN pg_namespace n ON n.oid = c.relnamespace
                    WHERE c.relname = 'idx_status_started'
                    AND n.nspname = 'public'
                ) THEN
                    CREATE INDEX idx_status_started
                    ON workflowexecution (status, started);
                END IF;
            END$$;
            """
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # Nothing to do because the index idx_status_started must have been created long before this migration
    pass
