"""Running incident number

Revision ID: ab333148350e
Revises: 0b80bda47ee2
Create Date: 2025-03-12 13:22:48.372003

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab333148350e"
down_revision = "0b80bda47ee2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.add_column(sa.Column("running_number", sa.Integer(), nullable=True))
        batch_op.create_index(
            "ix_incident_tenant_running_number",
            ["tenant_id", "running_number"],
            unique=True,
            postgresql_where=sa.text("running_number IS NOT NULL"),
            sqlite_where=sa.text("running_number IS NOT NULL"),
        )

    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "incident_prefix",
                sqlmodel.sql.sqltypes.AutoString(length=10),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_incident_tenant_running_number",
            postgresql_where=sa.text("running_number IS NOT NULL"),
            sqlite_where=sa.text("running_number IS NOT NULL"),
        )
        batch_op.drop_column("running_number")

    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.drop_column("incident_prefix")
    # ### end Alembic commands ###
