"""workflow is_test and workflowexecution is_test_run columns

Revision ID: 819927b7ccfa
Revises: 885ff6b12fed
Create Date: 2025-04-21 10:18:49.074198

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "819927b7ccfa"
down_revision = "885ff6b12fed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_test",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table("workflowexecution", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_test_run",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowexecution", schema=None) as batch_op:
        batch_op.drop_column("is_test_run")

    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.drop_column("is_test")

    # ### end Alembic commands ###
