"""Running incident number

Revision ID: ca51d82ad410
Revises: a82154690f35
Create Date: 2025-03-08 21:45:25.415316

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "ca51d82ad410"
down_revision = "a82154690f35"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alerttogroup")
    op.drop_table("group")
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.add_column(sa.Column("running_number", sa.Integer(), nullable=True))
    op.create_index(
        "ix_incident_tenant_running_number",
        "incident",
        ["tenant_id", "running_number"],
        unique=True,
        postgresql_where=text("running_number IS NOT NULL"),
        mysql_where=text("running_number IS NOT NULL"),
        sqlite_where=text("running_number IS NOT NULL"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.drop_column("running_number")

    op.create_table(
        "group",
        sa.Column("rule_id", sa.CHAR(length=32), nullable=True),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(), nullable=False),
        sa.Column("creation_time", sa.DATETIME(), nullable=False),
        sa.Column("group_fingerprint", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(["rule_id"], ["rule.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "alerttogroup",
        sa.Column("group_id", sa.CHAR(length=32), nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.Column("alert_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alert.id"],
        ),
        sa.ForeignKeyConstraint(["group_id"], ["group.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "alert_id"),
    )
    # ### end Alembic commands ###
