"""Add alertraw index and error

Revision ID: ca74b4a04371
Revises: a82154690f35
Create Date: 2025-03-06 10:46:23.453102

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca74b4a04371"
down_revision = "a82154690f35"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alertraw", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        # add
        # dismissed: bool = Field(default=False)
        # dismissed_at: datetime | None = Field(default=None)
        # dismissed_by: str | None = Field(default=None)

        # Get database connection to check dialect
        conn = op.get_bind()
        dialect_name = conn.dialect.name

        # Handle different database dialects
        if dialect_name == "mysql":
            batch_op.add_column(
                sa.Column(
                    "dismissed",
                    sa.Boolean(),
                    nullable=False,
                    server_default=sa.text("0"),
                )
            )
        elif dialect_name == "postgresql":
            batch_op.add_column(
                sa.Column(
                    "dismissed",
                    sa.Boolean(),
                    nullable=False,
                    server_default=sa.text("false"),
                )
            )
        else:
            # SQLite and others
            batch_op.add_column(
                sa.Column(
                    "dismissed", sa.Boolean(), nullable=False, server_default="false"
                )
            )

        batch_op.add_column(sa.Column("dismissed_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("dismissed_by", sa.String(), nullable=True))
        batch_op.create_index(
            "ix_alert_raw_tenant_id_error", ["tenant_id", "error"], unique=False
        )
        batch_op.create_index(
            "ix_alert_raw_tenant_id_timestamp", ["tenant_id", "timestamp"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_alertraw_error"), ["error"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_alertraw_tenant_id"), ["tenant_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alertraw", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alertraw_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_alertraw_error"))
        batch_op.drop_index("ix_alert_raw_tenant_id_timestamp")
        batch_op.drop_index("ix_alert_raw_tenant_id_error")
        batch_op.drop_column("error_message")
        batch_op.drop_column("error")
        batch_op.drop_column("dismissed_by")
        batch_op.drop_column("dismissed_at")
        batch_op.drop_column("dismissed")
    # ### end Alembic commands ###
