"""add step_id

Revision ID: 10db8cd02804
Revises: aa167915c4d6
Create Date: 2025-05-21 11:38:10.832807

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "10db8cd02804"
down_revision = "aa167915c4d6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowexecutionlog", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("step_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.create_index(
            "idx_workflowexecutionlog_workflow_execution_step_id",
            ["workflow_execution_id", "step_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowexecutionlog", schema=None) as batch_op:
        batch_op.drop_index("idx_workflowexecutionlog_workflow_execution_step_id")
        batch_op.drop_column("step_id")
    # ### end Alembic commands ###
