"""Topology Incident

Revision ID: 1c117f1accff
Revises: dcb7f88a04da
Create Date: 2025-01-01 15:14:55.998284

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c117f1accff"
down_revision = "dcb7f88a04da"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "incident_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )
        batch_op.add_column(sa.Column("incident_application", sa.Uuid(), nullable=True))

    with op.batch_alter_table("topologyapplication", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("repository", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )

    with op.batch_alter_table("topologyservice", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("namespace", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.drop_column("incident_application")
        batch_op.drop_column("incident_type")

    with op.batch_alter_table("topologyapplication", schema=None) as batch_op:
        batch_op.drop_column("repository")

    with op.batch_alter_table("topologyservice", schema=None) as batch_op:
        batch_op.drop_column("namespace")
    # ### end Alembic commands ###
