"""workflow is_test and workflowexecution is_test_run columns

Revision ID: 819927b7ccfa
Revises: 885ff6b12fed
Create Date: 2025-04-21 10:18:49.074198

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "819927b7ccfa"
down_revision = "885ff6b12fed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_test",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table("workflowexecution", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_test_run",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # Delete all related data for deprecated system test workflow tenant, workflow and related workflowexecutions, workfloecexutionlog, etc

    # First delete workflow execution logs
    op.execute(
        """
        DELETE FROM workflowexecutionlog 
        WHERE workflow_execution_id IN (
            SELECT id FROM workflowexecution WHERE workflow_id = 'test'
        )
    """
    )

    # Delete workflow-to-alert relations
    op.execute(
        """
        DELETE FROM workflowtoalertexecution
        WHERE workflow_execution_id IN (
            SELECT id FROM workflowexecution WHERE workflow_id = 'test'
        )
    """
    )

    # Delete workflow-to-incident relations
    op.execute(
        """
        DELETE FROM workflowtoincidentexecution
        WHERE workflow_execution_id IN (
            SELECT id FROM workflowexecution WHERE workflow_id = 'test'
        )
    """
    )

    # Delete workflow executions
    op.execute("DELETE FROM workflowexecution WHERE workflow_id = 'test'")

    # Delete workflow version
    op.execute("DELETE FROM workflowversion WHERE workflow_id = 'test'")

    # Delete the test workflow
    op.execute("DELETE FROM workflow WHERE id = 'test'")

    # Finally delete the system test tenant
    op.execute("DELETE FROM tenant WHERE id = 'system-test-workflow'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowexecution", schema=None) as batch_op:
        batch_op.drop_column("is_test_run")

    with op.batch_alter_table("workflow", schema=None) as batch_op:
        batch_op.drop_column("is_test")

    # ### end Alembic commands ###
