"""multi-level rule

Revision ID: 251862bec2ba
Revises: aff0128aa8f1
Create Date: 2025-03-16 13:58:26.193328

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "251862bec2ba"
down_revision = "aff0128aa8f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.add_column(sa.Column("multi_level", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "multi_level_property_name",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.drop_column("multi_level_property_name")
        batch_op.drop_column("multi_level")
    # ### end Alembic commands ###
