"""Few more indexes

Revision ID: dcb7f88a04da
Revises: 7297ae99cd21
Create Date: 2025-01-01 09:59:13.393588

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dcb7f88a04da"
down_revision = "7297ae99cd21"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.create_index(
            "idx_alert_tenant_timestamp_fingerprint",
            ["tenant_id", "timestamp", "fingerprint"],
            unique=False,
        )
        batch_op.create_index(
            "idx_fingerprint_timestamp", ["fingerprint", "timestamp"], unique=False
        )

    with op.batch_alter_table("lastalert", schema=None) as batch_op:
        batch_op.alter_column(
            "first_timestamp", existing_type=sa.DATETIME(), nullable=False
        )
        batch_op.create_index(
            "idx_lastalert_tenant_ordering",
            ["tenant_id", "first_timestamp", "alert_id", "fingerprint"],
            unique=False,
        )
        batch_op.create_index(
            "idx_lastalert_tenant_timestamp",
            ["tenant_id", "first_timestamp"],
            unique=False,
        )
        batch_op.create_index(
            "idx_lastalert_tenant_timestamp_new",
            ["tenant_id", "timestamp"],
            unique=False,
        )

    with op.batch_alter_table("lastalerttoincident", schema=None) as batch_op:
        batch_op.create_index(
            "idx_lastalerttoincident_tenant_fingerprint",
            ["tenant_id", "fingerprint", "deleted_at"],
            unique=False,
        )
        batch_op.create_index(
            "idx_tenant_deleted_fingerprint",
            ["tenant_id", "deleted_at", "fingerprint"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("lastalerttoincident", schema=None) as batch_op:
        batch_op.drop_index("idx_tenant_deleted_fingerprint")
        batch_op.drop_index("idx_lastalerttoincident_tenant_fingerprint")

    with op.batch_alter_table("lastalert", schema=None) as batch_op:
        batch_op.drop_index("idx_lastalert_tenant_timestamp_new")
        batch_op.drop_index("idx_lastalert_tenant_timestamp")
        batch_op.drop_index("idx_lastalert_tenant_ordering")
        batch_op.alter_column(
            "first_timestamp", existing_type=sa.DATETIME(), nullable=True
        )

    with op.batch_alter_table("alert", schema=None) as batch_op:
        batch_op.drop_index("idx_fingerprint_timestamp")
        batch_op.drop_index("idx_alert_tenant_timestamp_fingerprint")

    # ### end Alembic commands ###
