"""add rule assignee

Revision ID: 7c14f776ef6b
Revises: 90e3eababbf0
Create Date: 2025-06-04 10:43:04.805408

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c14f776ef6b"
down_revision = "90e3eababbf0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("assignee", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rule", schema=None) as batch_op:
        batch_op.drop_column("assignee")
    # ### end Alembic commands ###
