"""Convert incident name fields to text

Revision ID: c0880e315ebe
Revises: aff0128aa8f1
Create Date: 2025-03-20 09:37:38.596306

"""

import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c0880e315ebe"
down_revision = "aff0128aa8f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.alter_column(
            "user_generated_name",
            existing_type=sa.VARCHAR(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "ai_generated_name",
            existing_type=sa.VARCHAR(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

def downgrade() -> None:

    with op.batch_alter_table("incident", schema=None) as batch_op:
        batch_op.alter_column(
            "ai_generated_name",
            existing_type=sa.TEXT(),
            type_=sa.VARCHAR(255),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "user_generated_name",
            existing_type=sa.TEXT(),
            type_=sa.VARCHAR(255),
            existing_nullable=True,
        )
