"""Providers metadata

Revision ID: eddcb77eb6f3
Revises: 819927b7ccfa
Create Date: 2025-05-04 15:02:12.314043

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "eddcb77eb6f3"
down_revision = "819927b7ccfa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider", schema=None) as batch_op:
        batch_op.add_column(sa.Column("provider_metadata", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider", schema=None) as batch_op:
        batch_op.drop_column("provider_metadata")

    # ### end Alembic commands ###
