# Mock Nagios alert data for testing and documentation purposes.
ALERTS = [
    {
        "id": "nagios-host-1",
        "name": "Host Down: web-server-01",
        "status": "firing",
        "severity": "critical",
        "lastReceived": "2025-04-21T10:30:00.000000Z",
        "environment": "production",
        "service": "infrastructure",
        "source": ["nagios"],
        "message": "CRITICAL - Host web-server-01 is DOWN",
        "description": "Host web-server-01 is unreachable (PING CRITICAL - Packet loss = 100%)",
        "nagios": {
            "host_name": "web-server-01",
            "host_state": "DOWN",
            "host_address": "192.168.1.10",
            "check_command": "check_ping",
            "last_check": "2025-04-21T10:30:00Z",
            "current_attempt": "3/3",
            "state_type": "HARD",
            "notification_type": "PROBLEM",
        },
    },
    {
        "id": "nagios-service-1",
        "name": "Service Critical: HTTP on web-server-01",
        "status": "firing",
        "severity": "high",
        "lastReceived": "2025-04-21T10:35:00.000000Z",
        "environment": "production",
        "service": "web",
        "source": ["nagios"],
        "message": "CRITICAL - HTTP on web-server-01: Connection refused",
        "description": "HTTP CRITICAL - Connection refused on port 80",
        "nagios": {
            "host_name": "web-server-01",
            "service_description": "HTTP",
            "service_state": "CRITICAL",
            "host_address": "192.168.1.10",
            "check_command": "check_http",
            "last_check": "2025-04-21T10:35:00Z",
            "current_attempt": "3/5",
            "state_type": "HARD",
            "notification_type": "PROBLEM",
        },
    },
    {
        "id": "nagios-service-2",
        "name": "Service Warning: Disk Space on db-server-01",
        "status": "firing",
        "severity": "warning",
        "lastReceived": "2025-04-21T10:40:00.000000Z",
        "environment": "production",
        "service": "database",
        "source": ["nagios"],
        "message": "WARNING - Disk Space on db-server-01: 85% used",
        "description": "DISK WARNING - free space on /var: 15% (847 MB)",
        "nagios": {
            "host_name": "db-server-01",
            "service_description": "Disk Space /var",
            "service_state": "WARNING",
            "host_address": "192.168.1.20",
            "check_command": "check_disk",
            "last_check": "2025-04-21T10:40:00Z",
            "current_attempt": "1/5",
            "state_type": "SOFT",
            "notification_type": "PROBLEM",
        },
    },
]