ALERTS = {
    "host_name": "web-server-01",
    "service_description": "HTTP",
    "state": "CRITICAL",
    "state_type": "HARD",
    "plugin_output": "HTTP CRITICAL - Socket timeout after 10 seconds",
    "long_plugin_output": "Connection to web-server-01 port 80 timed out",
    "notification_type": "PROBLEM",
    "host_state": "UP",
    "host_address": "192.168.1.100",
    "timestamp": "1706300400",
    "current_attempt": "3",
    "max_attempts": "3",
    "duration": "0d 0h 5m 30s",
    "contact_name": "admin",
    "contact_email": "admin@example.com",
    "acknowledgement_author": "",
    "acknowledgement_comment": "",
    "service_url": "/nagios/cgi-bin/extinfo.cgi?type=2&host=web-server-01&service=HTTP",
}
