"""Mock alerts for AllQuiet provider testing."""

ALERTS_SIMULATION = [
    {
        "id": "aq-incident-001",
        "name": "AllQuiet incident: Database connection pool exhausted",
        "severity": "critical",
        "status": "firing",
        "lastReceived": "2024-01-15T14:30:00Z",
        "description": "Production database connection pool has reached its limit. New connections are being rejected.",
        "source": ["allquiet"],
        "url": "https://app.allquiet.app/incidents/aq-incident-001",
        "fingerprint": "aq-incident-001",
        "assignee": "on-call-engineer@company.com",
        "labels": ["production", "database", "critical"],
        "service": "backend-api",
        "environment": "production",
    },
    {
        "id": "aq-incident-002",
        "name": "AllQuiet incident: High memory usage on worker nodes",
        "severity": "warning",
        "status": "acknowledged",
        "lastReceived": "2024-01-15T13:15:00Z",
        "description": "Worker nodes are reporting memory usage above 85%. Risk of OOM kills.",
        "source": ["allquiet"],
        "url": "https://app.allquiet.app/incidents/aq-incident-002",
        "fingerprint": "aq-incident-002",
        "assignee": "sre-team@company.com",
        "labels": ["infrastructure", "memory"],
        "service": "worker-service",
        "environment": "production",
    },
    {
        "id": "aq-incident-003",
        "name": "AllQuiet incident: Payment service 5xx spike",
        "severity": "high",
        "status": "firing",
        "lastReceived": "2024-01-15T14:45:00Z",
        "description": "Payment service is returning 5xx errors at a rate of 12%. Error budget is being burned.",
        "source": ["allquiet"],
        "url": "https://app.allquiet.app/incidents/aq-incident-003",
        "fingerprint": "aq-incident-003",
        "assignee": "",
        "labels": ["payments", "api"],
        "service": "payment-service",
        "environment": "production",
    },
]
