

import glob
import os


def main():
    # Read all files from docs/providers/documentation folder
    files = glob.glob("./docs/providers/documentation/*", recursive=True)
    for file_path in files:
        # Extract provider name from file path
        provider_name = os.path.basename(file_path).replace("-provider.mdx", "")
        import_line = f"import AutoGeneratedSnippet from '/snippets/providers/{provider_name}-snippet-autogenerated.mdx';"
        use_line = f"<AutoGeneratedSnippet />"
        # if import_line not in the file, add it after second "---" line
        with open(file_path, "r") as file:
            lines = file.readlines()
            if import_line not in lines:
                count = 0
                for i, line in enumerate(lines):
                    if line == "---\n":
                        count += 1
                        if count == 2:
                            lines.insert(i + 1, import_line + "\n")
                            break  
                # if use_line not in the file, add it at the end of the file
                if use_line not in lines:
                    lines.append("\n" + use_line + "\n")
                with open(file_path, "w") as file:
                    file.writelines(lines)
    
if __name__ == "__main__":
    main()