"""Mock alerts for Vertex AI provider testing."""

ALERTS_SIMULATION = [
    {
        "id": "endpoint-abc123-model-xyz456",
        "name": "Vertex AI model unhealthy: text-bison-001 on production-endpoint",
        "severity": "critical",
        "status": "firing",
        "lastReceived": "2024-01-15T10:30:00Z",
        "description": "Deployed model 'text-bison-001' on endpoint 'production-endpoint' reported health state: UNHEALTHY",
        "source": ["vertexai"],
        "url": "https://console.cloud.google.com/vertex-ai/online-prediction/endpoints/endpoint-abc123",
        "fingerprint": "vertexai-model-endpoint-abc123-model-xyz456",
        "project": "my-gcp-project",
        "region": "us-central1",
        "endpoint_id": "endpoint-abc123",
        "deployed_model_id": "model-xyz456",
        "health_state": "UNHEALTHY",
    },
    {
        "id": "endpoint-def789",
        "name": "Vertex AI endpoint has no deployed models: staging-endpoint",
        "severity": "low",
        "status": "firing",
        "lastReceived": "2024-01-15T09:00:00Z",
        "description": "Endpoint 'staging-endpoint' has no deployed models.",
        "source": ["vertexai"],
        "url": "https://console.cloud.google.com/vertex-ai/online-prediction/endpoints/endpoint-def789",
        "fingerprint": "vertexai-endpoint-empty-endpoint-def789",
        "project": "my-gcp-project",
        "region": "us-central1",
        "endpoint_id": "endpoint-def789",
    },
    {
        "id": "endpoint-ghi012-model-jkl345",
        "name": "Vertex AI model unhealthy: gemini-pro on analytics-endpoint",
        "severity": "warning",
        "status": "firing",
        "lastReceived": "2024-01-15T11:15:00Z",
        "description": "Deployed model 'gemini-pro' on endpoint 'analytics-endpoint' reported health state: DEGRADED",
        "source": ["vertexai"],
        "url": "https://console.cloud.google.com/vertex-ai/online-prediction/endpoints/endpoint-ghi012",
        "fingerprint": "vertexai-model-endpoint-ghi012-model-jkl345",
        "project": "my-gcp-project",
        "region": "us-central1",
        "endpoint_id": "endpoint-ghi012",
        "deployed_model_id": "model-jkl345",
        "health_state": "DEGRADED",
    },
]
