ALERTS = {
    "model_high_error_rate": {
        "payload": {
            "version": "1.0",
            "incident": {
                "incident_id": "vertexai-err-001",
                "scoping_project_id": "my-gcp-project",
                "scoping_project_number": 123456789,
                "url": "https://console.cloud.google.com/monitoring/alerting/incidents/vertexai-err-001",
                "started_at": 0,
                "ended_at": 0,
                "state": "OPEN",
                "summary": "High error rate detected on Vertex AI model endpoint",
                "observed_value": "8.3",
                "resource": {
                    "type": "aiplatform.googleapis.com/Endpoint",
                    "labels": {
                        "endpoint_id": "1234567890123456789",
                        "location": "us-central1",
                        "project_id": "my-gcp-project",
                    },
                },
                "resource_type_display_name": "Vertex AI Endpoint",
                "resource_id": "1234567890123456789",
                "resource_display_name": "llm-serving-endpoint",
                "resource_name": "projects/123456789/locations/us-central1/endpoints/1234567890123456789",
                "metric": {
                    "type": "aiplatform.googleapis.com/prediction/online/error_count",
                    "displayName": "Online prediction error count",
                    "labels": {"error_type": "prediction_error"},
                },
                "metadata": {
                    "system_labels": {"severity": "CRITICAL"},
                    "user_labels": {"environment": "production", "model": "gemini-pro"},
                },
                "policy_name": "projects/123456789/alertPolicies/vertexai-error-policy",
                "policy_user_labels": {"team": "ml-platform", "severity": "CRITICAL"},
                "documentation": {
                    "subject": "Vertex AI Endpoint High Error Rate",
                    "content": "The error rate on the Vertex AI prediction endpoint has exceeded the threshold. Immediate attention required.",
                },
                "condition": {
                    "name": "projects/123456789/alertPolicies/vertexai-error-policy/conditions/1",
                    "displayName": "Error Rate > 5%",
                    "conditionThreshold": {
                        "filter": 'metric.type="aiplatform.googleapis.com/prediction/online/error_count" resource.type="aiplatform.googleapis.com/Endpoint"',
                        "comparison": "COMPARISON_GT",
                        "thresholdValue": 5.0,
                        "duration": "300s",
                        "trigger": {"count": 1},
                    },
                },
                "condition_name": "Error Rate > 5%",
                "threshold_value": "5.0",
            },
        },
        "parameters": {},
    },
    "model_high_latency": {
        "payload": {
            "version": "1.0",
            "incident": {
                "incident_id": "vertexai-lat-002",
                "scoping_project_id": "my-gcp-project",
                "scoping_project_number": 123456789,
                "url": "https://console.cloud.google.com/monitoring/alerting/incidents/vertexai-lat-002",
                "started_at": 0,
                "ended_at": 0,
                "state": "OPEN",
                "summary": "High latency detected on Vertex AI model endpoint predictions",
                "observed_value": "12500",
                "resource": {
                    "type": "aiplatform.googleapis.com/Endpoint",
                    "labels": {
                        "endpoint_id": "9876543210987654321",
                        "location": "us-central1",
                        "project_id": "my-gcp-project",
                    },
                },
                "resource_type_display_name": "Vertex AI Endpoint",
                "resource_id": "9876543210987654321",
                "resource_display_name": "text-generation-endpoint",
                "resource_name": "projects/123456789/locations/us-central1/endpoints/9876543210987654321",
                "metric": {
                    "type": "aiplatform.googleapis.com/prediction/online/latencies",
                    "displayName": "Online prediction latencies",
                    "labels": {"response_code": "OK"},
                },
                "metadata": {
                    "system_labels": {"severity": "WARNING"},
                    "user_labels": {"environment": "production", "model": "text-bison"},
                },
                "policy_name": "projects/123456789/alertPolicies/vertexai-latency-policy",
                "policy_user_labels": {"team": "ml-platform", "severity": "WARNING"},
                "documentation": {
                    "subject": "Vertex AI Endpoint High Latency",
                    "content": "Prediction latency on the Vertex AI endpoint has exceeded 10 seconds. This may indicate resource constraints or model issues.",
                },
                "condition": {
                    "name": "projects/123456789/alertPolicies/vertexai-latency-policy/conditions/1",
                    "displayName": "P99 Latency > 10s",
                    "conditionThreshold": {
                        "filter": 'metric.type="aiplatform.googleapis.com/prediction/online/latencies" resource.type="aiplatform.googleapis.com/Endpoint"',
                        "comparison": "COMPARISON_GT",
                        "thresholdValue": 10000.0,
                        "duration": "300s",
                        "trigger": {"count": 1},
                    },
                },
                "condition_name": "P99 Latency > 10s",
                "threshold_value": "10000.0",
            },
        },
        "parameters": {},
    },
    "model_endpoint_down": {
        "payload": {
            "version": "1.0",
            "incident": {
                "incident_id": "vertexai-down-003",
                "scoping_project_id": "my-gcp-project",
                "scoping_project_number": 123456789,
                "url": "https://console.cloud.google.com/monitoring/alerting/incidents/vertexai-down-003",
                "started_at": 0,
                "ended_at": 0,
                "state": "OPEN",
                "summary": "Vertex AI model endpoint prediction count dropped to zero",
                "observed_value": "0",
                "resource": {
                    "type": "aiplatform.googleapis.com/Endpoint",
                    "labels": {
                        "endpoint_id": "1111222233334444555",
                        "location": "us-east1",
                        "project_id": "my-gcp-project",
                    },
                },
                "resource_type_display_name": "Vertex AI Endpoint",
                "resource_id": "1111222233334444555",
                "resource_display_name": "production-llm-endpoint",
                "resource_name": "projects/123456789/locations/us-east1/endpoints/1111222233334444555",
                "metric": {
                    "type": "aiplatform.googleapis.com/prediction/online/prediction_count",
                    "displayName": "Online prediction request count",
                    "labels": {"response_code": "OK"},
                },
                "metadata": {
                    "system_labels": {"severity": "CRITICAL"},
                    "user_labels": {"environment": "production"},
                },
                "policy_name": "projects/123456789/alertPolicies/vertexai-availability-policy",
                "policy_user_labels": {"team": "ml-platform", "severity": "CRITICAL"},
                "documentation": {
                    "subject": "Vertex AI Endpoint Appears Down",
                    "content": "Prediction count has dropped to zero. The model endpoint may be down or unreachable.",
                },
                "condition": {
                    "name": "projects/123456789/alertPolicies/vertexai-availability-policy/conditions/1",
                    "displayName": "Prediction Count = 0",
                    "conditionThreshold": {
                        "filter": 'metric.type="aiplatform.googleapis.com/prediction/online/prediction_count" resource.type="aiplatform.googleapis.com/Endpoint"',
                        "comparison": "COMPARISON_LT",
                        "thresholdValue": 1.0,
                        "duration": "600s",
                        "trigger": {"count": 1},
                    },
                },
                "condition_name": "Prediction Count = 0",
                "threshold_value": "1.0",
            },
        },
        "parameters": {},
    },
    "model_monitoring_skew": {
        "payload": {
            "version": "1.0",
            "incident": {
                "incident_id": "vertexai-skew-004",
                "scoping_project_id": "my-gcp-project",
                "scoping_project_number": 123456789,
                "url": "https://console.cloud.google.com/monitoring/alerting/incidents/vertexai-skew-004",
                "started_at": 0,
                "ended_at": 0,
                "state": "OPEN",
                "summary": "Feature skew detected in Vertex AI model monitoring",
                "observed_value": "0.42",
                "resource": {
                    "type": "aiplatform.googleapis.com/Endpoint",
                    "labels": {
                        "endpoint_id": "5555666677778888999",
                        "location": "us-central1",
                        "project_id": "my-gcp-project",
                    },
                },
                "resource_type_display_name": "Vertex AI Endpoint",
                "resource_id": "5555666677778888999",
                "resource_display_name": "fraud-detection-endpoint",
                "resource_name": "projects/123456789/locations/us-central1/endpoints/5555666677778888999",
                "metric": {
                    "type": "aiplatform.googleapis.com/prediction/online/prediction_count",
                    "displayName": "Online prediction request count",
                    "labels": {},
                },
                "metadata": {
                    "system_labels": {"severity": "WARNING"},
                    "user_labels": {"environment": "production"},
                },
                "policy_name": "projects/123456789/alertPolicies/vertexai-skew-policy",
                "policy_user_labels": {"team": "ml-platform", "severity": "WARNING"},
                "documentation": {
                    "subject": "Vertex AI Model Feature Skew Detected",
                    "content": "Model monitoring has detected significant feature skew between training and serving data distributions.",
                },
                "condition": {
                    "name": "projects/123456789/alertPolicies/vertexai-skew-policy/conditions/1",
                    "displayName": "Feature Skew > 0.3",
                    "conditionThreshold": {
                        "filter": 'metric.type="aiplatform.googleapis.com/prediction/online/prediction_count"',
                        "comparison": "COMPARISON_GT",
                        "thresholdValue": 0.3,
                        "duration": "300s",
                        "trigger": {"count": 1},
                    },
                },
                "condition_name": "Feature Skew > 0.3",
                "threshold_value": "0.3",
            },
        },
        "parameters": {},
    },
}
