# A workflow that sync Keep workflows from a directory
name: "Sync Keep Workflows"

on:
    workflow_dispatch:
        inputs:
            keep_api_key:
              description: 'Keep API Key'
              required: false
            keep_api_url:
              description: 'Keep API URL'
              required: false
              default: 'https://api.keephq.dev'
    # push:
    #     paths:
    #       - 'examples/workflows/**'

jobs:
    sync-workflows:
        name: Sync workflows to Keep
        runs-on: ubuntu-latest
        # Use the Keep CLI image
        container:
            image: us-central1-docker.pkg.dev/keephq/keep/keep-cli:latest
        env:
            KEEP_API_KEY: ${{ secrets.KEEP_API_KEY || github.event.inputs.keep_api_key }}
            KEEP_API_URL: ${{ secrets.KEEP_API_URL || github.event.inputs.keep_api_url }}

        steps:
        - name: Check out the repo
          uses: actions/checkout@v2

        - name: Check Checkout Status
          if: ${{ success() }}
          run: echo "Repository checked out successfully."

        - name: Run Keep CLI
          run: |
            keep workflow apply -f examples/workflows
        
        - name: Check Keep CLI Status
          if: ${{ success() }}
          run: echo "Keep CLI command executed successfully."

        - name: Handle Keep CLI Failure
          if: ${{ failure() }}
          run: |
            echo "Keep CLI command failed. Please check the logs for details."
            exit 1
